services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:${DOZZLE_VERSION}
    restart: unless-stopped
    ports:
      - "${DOZZLE_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/tank/apps/config/dozzle:/data
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
